---
- name: Configure_Firewalld
  hosts: all
  become: true

  vars:
    zone_name: REJECT
#    ssh_port: 4312
#    allow_ssh_port:
#      semanage:
#        ports: "{{ ssh_port }}/tcp"
#        proto: tcp
#        setype: ssh_port_t
#        state: present

  tasks:
    - name: Create {{ zone_name }} firewall zone
      firewalld:
        zone: "{{ zone_name }}"
        state: present
        permanent: true

    - name: Allow SSH service
      firewalld:
        state: enabled
        zone: "{{ zone_name }}"
        service: ssh
        permanent: yes

    - name: Allow Samba service
      firewalld:
        state: enabled
        zone: "{{ zone_name }}"
        service: samba
        permanent: yes

    - name: Allow port 4312 only
      firewalld:
        state: enabled
        zone: "{{ zone_name }}"
        port: 4312/tcp
        permanent: yes

    - name: Drop all other traffic
      firewalld:
        zone: "{{ zone_name }}"
        state: enabled
        permanent: true
        immediate: true
        default: zone-policy
      notify: Restart Firewalld

#    - name: Allow port 4312 for SSH in SELinux
#      command: semanage port -a -t ssh_port_t -p tcp {{ ssh_port }}
#
#    - name: Modify ssh port
#      lineinfile:
#        path: /etc/ssh/sshd_config
#        regexp: '^#?Port .*'
#        line: 'Port 4312'
#        backup: yes
#        create: yes
#      notify: Restart SSH service

  handlers:
    - name: Restart Firewalld
      service:
        name: firewalld
        state: restarted

#    - name: Restart SSH service
#      service:
#       name: sshd
#       state: restarted