---
- name: Configure Firewall Zone
  hosts: centos
  become: true
  vars:
    firewall_zone: custom_ansible_zone

  tasks:
    # Create the firewall zone
    - name: Create firewall zone
      firewalld_zone:
        name: "{{ firewall_zone }}"
        state: present
        immediate: yes
        permanent: yes

    # Set the default policy to REJECT
    - name: Set default policy to REJECT
      firewalld:
        zone: "{{ firewall_zone }}"
        target: reject
        state: enabled
        permanent: yes
        immediate: yes

    # Allow SSH service in the firewall zone
    - name: Allow SSH service
      firewalld:
        zone: "{{ firewall_zone }}"
        service: ssh
        state: enabled
        permanent: yes
        immediate: yes

    # Allow Samba service on port 4312 in the firewall zone
    - name: Allow Samba service on port 4312
      firewalld:
        zone: "{{ firewall_zone }}"
        port: 4312/tcp
        state: enabled
        permanent: yes
        immediate: yes
