---
- name: Configure Firewall Zone
  hosts: all
  become: true
  vars:
    firewall_zone: my_zone

  tasks:
    # Create the firewall zone
    - name: Create firewall zone
      firewalld:
        zone: "{{ firewall_zone }}"
        state: present
        permanent: yes
        immediate: no

    # Set the default policy to REJECT
    - name: Set default policy to REJECT
      firewalld:
        zone: "{{ firewall_zone }}"
        permanent: yes
        immediate: yes
        rich_rule: 'rule family="ipv4" source NOT address="127.0.0.1/8" reject'

    # Allow SSH service in the firewall zone
    - name: Allow SSH service
      firewalld:
        zone: "{{ firewall_zone }}"
        service: ssh
        permanent: yes
        immediate: yes
        state: enabled

    # Allow Samba service on port 4312 in the firewall zone
    - name: Allow Samba service on port 4312
      firewalld:
        zone: "{{ firewall_zone }}"
        port: 4312/tcp
        permanent: yes
        immediate: yes
        state: enabled
