---
- name: Configure Firewall and SELinux
  hosts: all
  become: true

  tasks:
    - name: Create new firewall zone
      firewalld:
        zone: ansi_zone
        state: present
        permanent: true

    - name: Allow SSH traffic on port 4312
      firewalld:
        zone: ansi_zone
        port: 4312/tcp
        state: enabled
        permanent: true

    - name: Configure SSH to use port 4312
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port\s+\d+'
        line: 'Port 4312'
        state: present
        backup: yes

    - name: Allow Samba traffic on port 4312
      firewalld:
        zone: ansi_zone
        port: 4312/tcp
        state: enabled
        permanent: true

    - name: Configure Samba to use port 4312
      lineinfile:
        path: /etc/samba/smb.conf
        regexp: '^#?port\s+=\s+\d+'
        line: 'port = 4312'
        state: present
        backup: yes

    - name: Set SELinux policy to allow SSH traffic on port 4312
      seboolean:
        name: sshd_port_t
        set: true
        state: yes
        persistent: yes

    - name: Set SELinux policy to allow Samba traffic on port 4312
      seport:
        proto: tcp
        port: 4312
        setype: samba_port_t
        state: enabled

    - name: Drop all other traffic
      firewalld:
        zone: ansi_zone
        state: enabled
        permanent: true
        rich_rule: rule family="ipv4" source address="0.0.0.0/0" drop
      notify: restart firewalld

  handlers:
    - name: restart firewalld
      service:
        name: firewalld
        state: restarted
      notify: notify user

    - name: notify user
      debug:
        msg: "Firewall has been configured and firewalld service has been restarted. SELinux policies have been modified to allow traffic on port 4312."
