---
- name: Configure Firewall
  hosts: all
  become: true
  
  tasks:
    - name: Create new firewall zone
      firewalld:
        zone: new_zone
        state: present
        permanent: true
      become: true
      
    - name: Allow SSH traffic
      firewalld:
        zone: new_zone
        service: ssh
        state: enabled
        permanent: true
      
    - name: Allow Samba traffic
      firewalld:
        zone: new_zone
        service: samba
        state: enabled
        permanent: true
      
    - name: Reject all other traffic
      firewalld:
        zone: new_zone
        state: enabled
        permanent: true
        rich_rule: rule family="ipv4" source address="0.0.0.0/0" drop
