---
- name: Configure Firewalld
  hosts: all
  become: true

  tasks:
    - name: Create new firewall zone
      firewalld:
        zone: REJECT
        state: present
        target: "%%REJECT%%"
        permanent: true
        interfaces: ens33

    - name: Allow SSH
      firewalld:
        state: enabled
        zone: REJECT
        service: ssh
        permanent: yes

    - name: Allow Samba
      firewalld:
        state: enabled
        zone: REJECT
        service: samba
        permanent: yes

    - name: Allow port 4312
      firewalld:
        state: enabled
        zone: REJECT
        port: 4312/tcp
        permanent: yes

    - name: Drop all other traffic
      firewalld:
        zone: REJECT
        state: enabled
        permanent: true
        rich_rule: rule family="ipv4" source address="0.0.0.0/0" drop
      notify: Restart Firewalld

  handlers:
    - name: Restart Firewalld
      service:
        name: firewalld
        state: restarted


#CAN'T SSH INTO THEM FFS!!!