---
- name: Add /data/dir to fstab
  hosts: all
  become: true

  tasks:
    - name: Mount to fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^/dev/sd.* /data/mount.*'
        line: '/dev/sdb /data/mount ext4 defaults 0 0'
        state: present