---
- name: Configure Samba share for fonok
  hosts: all
  become: true

  vars:
    smb_share_name: "fontos"
    smb_share_path: "/data/fontos"
    smb_share_user: "fonok"
    smb_share_group: "users"
    smb_share_mode: "0775"
    smb_share_password: "smbpass"

  tasks:
    - name: Install Samba
      yum:
        name: samba
        state: present

    - name: Create user fonok
      user:
        name: "{{ smb_share_user }}"
        state: present
        createhome: no
        password: "{{ smb_share_password | password_hash('sha512') }}"

    - name: Create Samba directory
      file:
        path: "{{ smb_share_path }}"
        state: directory
        mode: "{{ smb_share_mode }}"
        owner: "{{ smb_share_user }}"
        group: "{{ smb_share_group }}"

    - name: Configure Samba share
      lineinfile:
        path: /etc/samba/smb.conf
        line: "{{ item }}"
      with_items:
        - "[{{ smb_share_name }}}"
        - "   path = {{ smb_share_path }}"
        - "   valid users = {{ smb_share_user }}"
        - "   read only = no"
        - "   create mask = 0644"
        - "   directory mask = 0755"
      notify:
        - restart Samba

  handlers:
    - name: restart Samba
      service:
        name: smbd
        state: restarted
