---
- name: Configure Samba share for fonok
  hosts: all
  become: true

  vars:
    smb_share_name: "fontos"
    smb_share_path: "/data/fontos"
    smb_share_user: "fonok"
    smb_share_group: "fonok"
    smb_share_mode: "0775"
    samba_password: "smbpass"

  tasks:
    - name: Install Samba
      yum:
        name: samba
        state: present
    
    - name: Start and enable smb service
      systemd:
        name: smb
        enabled: yes
        state: started

    - name: Check if user exists
      shell: id -u fonok > /dev/null 2>&1
      register: user_exists
      ignore_errors: true

    - name: Create user if it doesn't exist
      user:
        name: fonok
        password: "{{ 'fonokpw' | password_hash('sha512') }}"
        createhome: no
      when: user_exists.rc != 0

    - name: Set Samba password
      expect:
        command: smbpasswd -a fonok
        responses:
          'New SMB password:': '{{ samba_password }}\n'
          'Retype new SMB password:': '{{ samba_password }}\n'
      when: user_exists.rc != 0

    - name: Print status message
      debug:
        msg: "User fonok {{ 'created with password fonokpw and Samba password smbpass.' if user_exists.rc != 0 else 'already exists.' }}"

    - name: Create Samba directory
      file:
        path: "{{ smb_share_path }}"
        state: directory
        mode: "{{ smb_share_mode }}"
        owner: "{{ smb_share_user }}"
        group: "{{ smb_share_group }}"
        setype: "samba_share_t"

    - name: Configure Samba share
      lineinfile:
        path: /etc/samba/smb.conf
        line: "{{ item }}"
      with_items:
        - "[{{ smb_share_name }}]"
        - "path = {{ smb_share_path }}"
        - "valid users = {{ smb_share_user }}"
        - "read only = no"
        - "create mask = 0644"
        - "directory mask = 0755"
      notify:
        - restart Samba

    - name: Enable Samba in firewall
      firewalld:
        service: samba
        permanent: yes
        state: enabled
      notify: 
       - Restart firewalld service

  handlers:
    - name: restart Samba
      service:
        name: smb
        state: restarted
    
    - name: Restart firewalld service
      service:
        name: firewalld
        state: restarted
